### ISSUE TITLE
[EPIC] Next release (v0.6.1)

### ISSUE THREAD

**Issue by tzdybal** [rollkit/go-da#92]
This epic summarizes changes we plan to include in next release of go-da, and also helps keep track of issues across repositories. 

### Changes
- [x] Rename `GetIDs` in protobuf (see: https://github.com/rollkit/go-da/pull/51) 
- [x] #93
  - for some context: https://github.com/rollkit/rollkit/issues/1821
  - key name is implementation specific option; we need more generic solution
- [x] #96
- [x] #101
- [x] create a release

### Issues in other repos
- rollkit
  - [x] https://github.com/rollkit/rollkit/pull/1852
  - [x] https://github.com/rollkit/rollkit/pull/1853
  - [x] https://github.com/rollkit/rollkit/issues/1821
- celestia-node
  - [ ] https://github.com/celestiaorg/celestia-node/issues/3743
  - [ ] https://github.com/celestiaorg/celestia-node/pull/3750
- local-da
  - [x] all the implementation changes are derived from `DummyDA` implementation from go-da

**Comment by Manav-Aggarwal** [comment]
Closing this since go-da v0.6.1 is out
